const womensWatch2 = [
    {
      id: "40",
      cName: "Fosssil",
      title: "Rose Gold Dial Watch-ES4879",
      about: "",
      price: "₹7,795",
      offPrice: "",
      img: "/images/w-watch5.jpg",
      img1: "/images/w-watch5.1.jpg",
      img2: "/images/w-watch5.2.jpg",
      img3: "/images/w-watch5.3.jpg",
    }, {
      id: "41",
      cName: "Sonata",
      title: "White Dial  Watch-8976SL15l",
      about: "",
      price: "₹1,750",
      offPrice: "",
      img: "/images/w-watch6.jpg",
      img1: "/images/w-watch6.1.jpg",
      img2: "/images/w-watch6.2.jpg",
      img3: "/images/w-watch6.3.jpg",
    }, {
      id: "42",
      cName: "Casio",
      title: "Analog Black Dial Watch-VT01GL",
      about: "",
      price: "₹5,650",
      offPrice: "",
      img: "/images/w-watch7.jpg",
      img1: "/images/w-watch7.1.jpg",
      img2: "/images/w-watch7.2.jpg",
      img3: "/images/w-watch7.3.jpg",
    }, {
      id: "43",
      cName: "Daniel Klein",
      title: "Analog Women's Watch",
      about: "",
      price: "₹3,299",
      offPrice: "",
      img: "/images/w-watch8.jpg",
      img1: "/images/w-watch8.1.jpg",
      img2: "/images/w-watch8.2.jpg",
      img3: "/images/w-watch8.3.jpg",
    },
  ];

  export default womensWatch2;
