const womensShoes2 = [
    {
      id: "48",
      cName: "DREAM PAIRS",
      title: "Platform Wedge Sneakers Ankle",
      about: "",
      price: "₹11,206",
      offPrice: "",
      img: "/images/Wshoes5.jpg",
      img1: "/images/Wshoes5.1.jpg",
      img2: "/images/Wshoes5.2.jpg",
      img3: "/images/Wshoes5.3.jpg",
    },
    {
      id: "49",
      cName: "ECCO",
      title: "Slip-On Formal Shoes|2170452",
      about: "",
      price: "₹9,999",
      offPrice: "",
      img: "/images/Wshoes6.jpg",
      img1: "/images/Wshoes6.1.jpg",
      img2: "/images/Wshoes6.2.jpg",
      img3: "/images/Wshoes6.3.jpg",
    },
    {
      id: "50",
      cName: "Red Tape",
      title: "Women White/Blue Sneakers",
      about: "",
      price: "₹3,599",
      offPrice: "",
      img: "/images/Wshoes7.jpg",
      img1: "/images/Wshoes7.1.jpg",
      img2: "/images/Wshoes7.2.jpg",
      img3: "/images/Wshoes7.3.jpg",
    },
    {
      id: "51",
      cName: "Nike",
      title: "Womens Jordan Ma2 Sneaker",
      about: "",
      price: "₹6,950",
      offPrice: "",
      img: "/images/Wshoes8.jpg",
      img1: "/images/Wshoes8.1.jpg",
      img2: "/images/Wshoes8.2.jpg",
      img3: "/images/Wshoes8.3.jpg",
    },
  ];

  export default womensShoes2;
