const womensWatch = [
    {
      id: "36",
      cName: "CASIO",
      title: "Analog Rose Gold Dial-E157MR",
      about: "",
      price: "₹5,246",
      offPrice: "",
      img: "/images/w-watch1.jpg",
      img1: "/images/W-watch-1.1.jpg",
      img2: "/images/W-watch-1.2.jpg",
      img3: "/images/W-watch-1.3.jpg",
    }, {
      id: "37",
      cName: "TITAN",
      title: "Analog Black Dial-NL2480SM02",
      about: "",
      price: "₹3,145",
      offPrice: "",
      img: "/images/w-watch2.jpg",
      img1: "/images/w-watch2.1.jpg",
      img2: "/images/w-watch2.2.jpg",
      img3: "/images/w-watch2.3.jpg",
    },
    {
      id: "38",
      cName: "French Connection",
      title: "Analog Dial Women's Watch",
      about: "",
      price: "₹1,399",
      offPrice: "",
      img: "/images/w-watch3.jpg",
      img1: "/images/w-watch3.1.jpg",
      img2: "/images/w-watch3.2.jpg",
      img3: "/images/w-watch3.3.jpg",
    }, {
      id: "39",
      cName: "Fastrack",
      title: "Analog Black Dial-38024PP25",
      about: "",
      price: "₹1,249",
      offPrice: "",
      img: "/images/w-watch4.jpg",
      img1: "/images/w-watch4.1.jpg",
      img2: "/images/w-watch4.2.jpg",
      img3: "/images/w-watch4.3.jpg",
    },
  ];

  export default womensWatch;