const womensCloth2 = [
    {
      id: "32",
      cName: "ANNI DESIGNER",
      title: "Cotton Blend  Anarkali Kurta",
      about: "",
      price: "₹659",
      offPrice: "₹1259",
      img: "/images/women(5).jpg",
      img1: "/images/women(5.1).jpg",
      img2: "/images/women(5.2).jpg",
      img3: "/images/women(5.3).jpg",
    }, {
      id: "33",
      cName: "Greciilooks",
      title: "Western Dresses Knee-Length",
      about: "",
      price: "₹399",
      offPrice: "₹889",
      img: "/images/women(6).jpg",
      img1: "/images/women(6.1).jpg",
      img2: "/images/women(6.2).jpg",
      img3: "/images/women(6.3).jpg",
    },
    {
      id: "34",
      cName: "J B Fashion",
      title: "Western Top with halfSleeves",
      about: "",
      price: "₹419",
      offPrice: "₹850",
      img: "/images/women(7).jpg",
      img1: "/images/women(7.1).jpg",
      img2: "/images/women(7.2).jpg",
      img3: "/images/women(7.3).jpg",
    }, {
      id: "35",
      cName: "Greciilooks",
      title: "Lycra Striped Top  Half Sleeves",
      about: "",
      price: "₹379",
      offPrice: "₹799",
      img: "/images/women(8).jpg",
      img1: "/images/women(8.1).jpg",
      img2: "/images/women(8.2).jpg",
      img3: "/images/women(8.3).jpg",
    },
  ];

  export default womensCloth2;