const mensWatches2 = [
    {
      id: "12",
      cName: "Diesel",
      title: "Analog Black Over sized dial",
      about: "",
      price: "₹19,999",
      offPrice: "",
      img: "/images/M-watch-5.jpg",
      img1: "/images/M-watch-5.1.jpg",
      img2: "/images/M-watch-5.2.jpg",
      img3: "/images/M-watch-5.3.jpg",
    },
    {
      id: "13",
      cName: "Tommy Hilfiger",
      title: "Analog Blue Dial ",
      about: "",
      price: "₹14,750",
      offPrice: "",
      img: "/images/M-watch-6.jpg",
      img1: "/images/M-watch-6.1.jpg",
      img2: "/images/M-watch-6.2.jpg",
      img3: "/images/M-watch-6.3.jpg",
    }, {
      id: "14",
      cName: "G Shock ",
      title: "Analog-Digital Black-GA-900C",
      about: "",
      price: "₹10,999",
      offPrice: "",
      img: "/images/M-watch-7.jpg",
      img1: "/images/M-watch-7.1.jpg",
      img2: "/images/M-watch-7.2.jpg",
      img3: "/images/M-watch-7.3.jpg",
    },
    {
      id: "15",
      cName: "French Connection",
      title: "Analog Blue Dial-FCA03-4l",
      about: "",
      price: "₹6,599",
      offPrice: "",
      img: "/images/M-watch-8.jpg",
      img1: "/images/M-watch-8.1.jpg",
      img2: "/images/M-watch-8.2.jpg",
      img3: "/images/M-watch-8.3.jpg",
    },
  ];

  export default mensWatches2;