const mensCloth2 = [
    {
      id: "4",
      cName: "Rozden",
      title: "Men's Oversized T-shirt",
      about: "",
      price: "₹499",
      offPrice: "₹799",
      img: "/images/mens (5).jpg",
      img1: "/images/mens (5.1).jpg",
      img2: "/images/mens (5.2).jpg",
      img3: "/images/mens (5.3).jpg",
    },
    {
      id: "5",
      cName: "PUMA",
      title: "Men's Fit T-shirt",
      about: "",
      price: "₹690",
      offPrice: "₹989",
      img: "/images/mens (6).jpg",
      img1: "/images/mens (6.1).jpg",
      img2: "/images/mens (6.2).jpg",
      img3: "/images/mens (6.3).jpg",
    },
    {
      id: "6",
      cName: "Aspire",
      title: "Men's t-shirt",
      about: "",
      price: "₹475",
      offPrice: "₹785",
      img: "/images/mens (7).jpg",
      img1: "/images/mens (7.1).jpg",
      img2: "/images/mens (7.2).jpg",
      img3: "/images/mens (7.3).jpg",
    },
    {
      id: "7",
      cName: "Planet Superheros",
      title: "Thor Long Sleeve T-shirt",
      about: "",
      price: "₹789",
      offPrice: "₹1279",
      img: "/images/mens (8).jpg",
      img1: "/images/mens (8.1).jpg",
      img2: "/images/mens (8.2).jpg",
      img3: "/images/mens (8.3).jpg",
    },
  ];

  export default mensCloth2;