const mensShoes2 = [
    {
      id: "20",
      cName: "Nike",
      title: "White Running Shoes(DD02101)",
      about: "",
      price: "₹6,430",
      offPrice: "",
      img: "/images/Mshoes-5.jpg",
      img1: "/images/Mshoes-5.1.jpg",
      img2: "/images/Mshoes-5.2.jpg",
      img3: "/images/Mshoes-5.3.jpg",
    }, {
      id: "21",
      cName: "Woodland",
      title: "Men's Leather Casual Shoes ",
      about: "",
      price: "₹2,399",
      offPrice: "",
      img: "/images/Mshoes-6.jpg",
      img1: "/images/Mshoes-6.1.jpg",
      img2: "/images/Mshoes-6.2.jpg",
      img3: "/images/Mshoes-6.3.jpg",
    }, {
      id: "22",
      cName: "Puma",
      title: "Backcourt Black-High Risk Red",
      about: "",
      price: "₹6,599",
      offPrice: "",
      img: "/images/Mshoes-7.jpg",
      img1: "/images/Mshoes-6.1.jpg",
      img2: "/images/Mshoes-6.2.jpg",
      img3: "/images/Mshoes-6.3.jpg",
    }, {
      id: "23",
      cName: "Nike",
      title: "Air Pegasus 39 Running Shoe",
      about: "",
      price: "₹11,950",
      offPrice: "",
      img: "/images/Mshoes-8.jpg",
      img1: "/images/Mshoes-8.1.jpg",
      img2: "/images/Mshoes-8.2.jpg",
      img3: "/images/Mshoes-8.3.jpg",
    },
  ];

  export default mensShoes2;