const mensWatches = [
    {
      id: "8",
      cName: "CASIO",
      title: "G-Shock  Men's Watch",
      about: "",
      price: "₹10,499",
      offPrice: "",
      img: "/images/M-watch-1.jpg",
      img1: "/images/M-watch-1.1.jpg",
      img2: "/images/M-watch-1.2.jpg",
      img3: "/images/M-watch-1.3.jpg",
    },
    {
      id: "9",
      cName: "Amazfit",
      title: "GTS2 Mini  Smart Watch",
      about: "",
      price: "₹2000",
      offPrice: "",
      img: "/images/M-watch-2.jpg",
      img1: "/images/M-watch-2.1.jpg",
      img2: "/images/M-watch-2.2.jpg",
      img3: "/images/M-watch-2.3.jpg",
    }, {
      id: "10",
      cName: "TITAN",
      title: "Titan Neo Black Dial",
      about: "",
      price: "₹1199",
      offPrice: "",
      img: "/images/M-watch-3.jpg",
      img1: "/images/M-watch-3.1.jpg",
      img2: "/images/M-watch-3.2.jpg",
      img3: "/images/M-watch-3.3.jpg",
    },
    {
      id: "11",
      cName: "TIMEX",
      title: "Automatic Analog Brown Dial",
      about: "",
      price: "₹12,999",
      offPrice: "",
      img: "/images/M-watch-4.jpg",
      img1: "/images/M-watch-4.1.jpg",
      img2: "/images/M-watch-4.2.jpg",
      img3: "/images/M-watch-4.3.jpg",
    },
  ];

  export default mensWatches;